# Generated by Django 6.1.1 on 2026-10-02 06:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EndpointGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('min_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True)),
                ('os_name', models.CharField(max_length=100)),
                ('os_build', models.CharField(max_length=50)),
                ('last_reported_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endpoints', to='patchmgr.endpointgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kb_number', models.CharField(max_length=20)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('target_os', models.CharField(max_length=100)),
                ('fixed_build', models.CharField(blank=True, max_length=50)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('download_url', models.URLField(blank=True, max_length=500)),
                ('is_error_reported', models.BooleanField(default=False)),
                ('cves', models.ManyToManyField(blank=True, related_name='patches', to='patchmgr.cve')),
            ],
        ),
        migrations.CreateModel(
            name='PatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '미적용'), ('applied', '적용'), ('error', '오류'), ('rolled_back', '롤백')], default='pending', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_statuses', to='patchmgr.endpoint')),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='patchmgr.patch')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('delay_minutes', models.PositiveIntegerField(default=0)),
                ('rollback_error_rate', models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_stages', to='patchmgr.endpointgroup')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='patchmgr.policy')),
            ],
            options={
                'ordering': ['policy', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('running', '진행 중'), ('completed', '완료'), ('rolled_back', '롤백됨')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='patchmgr.patch')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='patchmgr.policy')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='patchmgr.policystage')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vendor', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'vendor'), name='uniq_software_name_vendor')],
            },
        ),
        migrations.CreateModel(
            name='InstalledSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_software', to='patchmgr.endpoint')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='patchmgr.software')),
            ],
        ),
        migrations.CreateModel(
            name='AffectedSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_start', models.CharField(blank=True, max_length=100)),
                ('version_end_excluding', models.CharField(blank=True, max_length=100)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_software', to='patchmgr.cve')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_by', to='patchmgr.software')),
            ],
        ),
        migrations.AddConstraint(
            model_name='patch',
            constraint=models.UniqueConstraint(fields=('kb_number', 'target_os'), name='uniq_patch_kb_os'),
        ),
        migrations.AddConstraint(
            model_name='patchstatus',
            constraint=models.UniqueConstraint(fields=('endpoint', 'patch'), name='uniq_patchstatus_endpoint_patch'),
        ),
        migrations.AddConstraint(
            model_name='policystage',
            constraint=models.UniqueConstraint(fields=('policy', 'order'), name='uniq_policystage_policy_order'),
        ),
        migrations.AddConstraint(
            model_name='installedsoftware',
            constraint=models.UniqueConstraint(fields=('endpoint', 'software'), name='uniq_installed_endpoint_software'),
        ),
    ]
