# Generated by Django 6.1.1 on 2026-10-02 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchmgr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affectedsoftware',
            name='version_start',
        ),
        migrations.AddField(
            model_name='affectedsoftware',
            name='version_end_including',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='affectedsoftware',
            name='version_exact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='affectedsoftware',
            name='version_start_excluding',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='affectedsoftware',
            name='version_start_including',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='SoftwareCpe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpes', to='patchmgr.software')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('software', 'vendor', 'product'), name='uniq_softwarecpe')],
            },
        ),
    ]
