# Generated by Django 6.1.1 on 2026-10-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchmgr', '0002_remove_affectedsoftware_version_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='deployment',
            name='stage_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='deployment',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'running')), fields=('patch',), name='uniq_running_deployment_per_patch'),
        ),
    ]
